=== Ruckwind/SubMicroTrading/Model/xml/model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Model">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="InternalModel"/>
        <xs:element ref="FixModels"/>
        <xs:element ref="Codecs"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="InternalModel">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Sizes"/>
        <xs:element maxOccurs="unbounded" ref="Instruction"/>
        <xs:element ref="Types"/>
        <xs:element ref="Events"/>
      </xs:sequence>
      <xs:attribute name="root" use="required" type="xs:NCName"/>
      <xs:attribute name="version" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Sizes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="DefaultSize"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="DefaultSize">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="val" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Instruction" type="xs:NCName"/>
  <xs:element name="Types">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Type">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Description"/>
        <xs:element minOccurs="0" ref="Default"/>
        <xs:element maxOccurs="unbounded" ref="Entry"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Default">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Attribute"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Events">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Base"/>
        <xs:element maxOccurs="unbounded" ref="Event"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Base">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Attribute"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Event">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Attribute"/>
      </xs:sequence>
      <xs:attribute name="extends" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="FixModels">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="FixVersion"/>
        <xs:element maxOccurs="unbounded" ref="FixModel"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FixVersion">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Entry"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FixModel">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element maxOccurs="unbounded" ref="Attribute"/>
        <xs:element ref="Dictionary"/>
        <xs:element ref="StrandardHeader"/>
        <xs:element ref="StandardTrailer"/>
        <xs:element maxOccurs="unbounded" ref="FixMessage"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:decimal"/>
      <xs:attribute name="modelVersionNumber" use="required" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Dictionary">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Tag"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="StrandardHeader">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Tag"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="StandardTrailer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Tag"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FixMessage">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Tag"/>
      </xs:sequence>
      <xs:attribute name="extends" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Codecs">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="Codec">
          <xs:sequence>
            <xs:element ref="ExchangeCodecs"/>
            <xs:element ref="ClientCodecs"/>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="ExchangeCodecs" type="Codec"/>
  <xs:element name="ClientCodecs" type="Codec"/>
  <xs:element name="Description" type="xs:string"/>
  <xs:element name="Entry">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Attribute"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="value" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Attribute">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="typeId" use="required" type="xs:NCName"/>
      <xs:attribute name="value" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Attribute">
    <xs:complexType>
      <xs:attribute name="mandatory" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:NCName"/>
      <xs:attribute name="tag" type="xs:integer"/>
      <xs:attribute name="typeId" use="required"/>
      <xs:attribute name="value" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tag">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:integer"/>
      <xs:attribute name="mand" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:NCName"/>
      <xs:attribute name="src" type="xs:NCName"/>
      <xs:attribute name="type" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Codec">
    <xs:sequence>
      <xs:element ref="Codec"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Codec">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="Map"/>
        <xs:sequence>
          <xs:element maxOccurs="unbounded" ref="ComplexType"/>
          <xs:element ref="MessageMap"/>
        </xs:sequence>
      </xs:choice>
      <xs:attribute name="extends" type="xs:NCName"/>
      <xs:attribute name="fix" use="required" type="xs:decimal"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="type" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Map">
    <xs:complexType>
      <xs:attribute name="decode" use="required"/>
      <xs:attribute name="fixMessageId" use="required" type="xs:NCName"/>
      <xs:attribute name="tagId" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ComplexType">
    <xs:complexType>
      <xs:attribute name="tag" use="required" type="xs:integer"/>
      <xs:attribute name="typeId" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="MessageMap">
    <xs:complexType>
      <xs:attribute name="eventId" use="required" type="xs:NCName"/>
      <xs:attribute name="fixMessageId" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Ruckwind/SubMicroTrading/Model/xml/model.xml
<?xml version="1.0"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///c:/Working/dev/NewProj/Model/xml/model.xsd">

    <!--
        fix sub groups have now been added, but restrictions are
        
        a) the counter must be the first entry directly preceeding the grp as in fast fix sequences
        b) fix subgroup must have same name as model sub group
        c) ALL possible fix entries in repeating group must be in the fix sub grp definition
           otherwise it can trigger early return from sub grp processing which stops on unexpected tag
           These tags dont need to be added to the internal model tho
           
        d) MUST BE CAREFUL, WHEN EXCHANGE CHANGE FIX SUB EVENTS THEY MUST BE UPDATED IN MODEL

        WARNING : SubGroups ... the first field in the sub group MUST be in correct order as its used to switch to next entry
    -->

    <InternalModel version="1.0.0" dir="../Generated/model/internal/version" rootPackage="com.rr.model.generated.internal">

        <!-- internal model values based on fix 4.4 -->

        <Sizes> <!-- will be placed into an OM size enum file -->
            @INCLUDE ./xml/model.sizes.xml DEFAULT_SIZES_CONSTANTS

            @INCLUDE ./xml/model.euronext.cash.utp.xml EURONEXT_CASH_UTP_CONSTANTS

            @INCLUDE ./xml/model.lse.millenium.xml LSE_MILLENIUM_CONSTANTS

            @INCLUDE ./xml/model.eurex.eti.xml EUREX_ETI_CONSTANTS

            @INCLUDE ./xml/model.cme.sbe.xml CME_CONSTANTS

            @INCLUDE ./xml/model.pitch.xml PITCH_CONSTANTS

            @INCLUDE ./xml/model.soup.xml SOUP_CONSTANTS
        </Sizes>


        <Instruction>RestrictMultiValueFieldsToSingleValue</Instruction>

        <Types>
            @INCLUDE ./xml/model.types.xml TYPES

            @INCLUDE ./xml/model.euronext.cash.utp.xml EURONEXT_CASH_UTP_TYPES

            @INCLUDE ./xml/model.lse.millenium.xml LSE_MILLENIUM_TYPES

            @INCLUDE ./xml/model.eurex.eti.xml EUREX_ETI_TYPES

            @INCLUDE ./xml/model.pitch.xml PITCH_TYPES

            @INCLUDE ./xml/model.soup.xml SOUP_TYPES
        </Types>

        <!-- if no attribute name supplied then typeId used to generate name -->
        <!--  attribute name used as a default for mapping to/from fix -->


        <!--  if ViewString is used their must be reusableString attribute named buf in event -->

        <!--  Attribute has optional attr outbound=[delegate|seperate]

              if any attr have delegate market side event then create Update interface
              marketside then doesnt implement Write interface only the Update interface

              "seperate" -> attr in inbound and outbound events may be different

              type : char | boolean | int | short | double | float | date | viewstring | reusablestring\[nnn\] | UTCTimestamp | InternalTypeId
        -->

        <Events>
            @INCLUDE ./xml/model.events.xml EVENTS

            @INCLUDE ./xml/model.events.strats.xml STRATS_EVENTS

            @INCLUDE ./xml/model.euronext.cash.utp.xml EURONEXT_CASH_UTP_EVENTS

            @INCLUDE ./xml/model.eurex.eti.xml EUREX_ETI_EVENTS

            @INCLUDE ./xml/model.lse.millenium.xml LSE_MILLENIUM_EVENTS

            @INCLUDE ./xml/model.lse.itch.xml LSE_ITCH_EVENTS

            @INCLUDE ./xml/model.pitch.xml PITCH_EVENTS

            @INCLUDE ./xml/model.soup.xml SOUP_EVENTS

        </Events>
    </InternalModel>

    <!--
         Fix Model (depends on Internal Model Schema)

            Model : [InternalModelVersion] [FixModel]+

            FixModel : [Id] [FixVersion] [modelVersionNumber] [FixHelper] [Dictionary] [FixMessage]*
            Dictionary = [Tag]* [SimpleFormatters]* [ComplexFormatters]*
            FixMessage = [Id] [FixMessageElements]*
            FixMessageElement = [Tag] (Priority) | [RepeatingGroup]
            RepeatingGroup = [GroupStart][CountTag][Tag]*[GroupEnd]
            Tag : [Id] [Name]
     -->

    <FixModels version="1.0.0" dir="../Generated/model/fix/version" rootPackage="com.rr.model.generated.fix">

        <FixVersion>
            <Entry name="4.0" value="4.0"/>
            <Entry name="4.2" value="4.2"/>
            <Entry name="4.4" value="4.4"/>
            <Entry name="5.0" value="5.0"/>
            <Entry name="MD4.4" value="4.4"/>
            <Entry name="MD5.0" value="5.0"/>
            <Entry name="DC4.4" value="4.4"/>
            <Entry name="MS4.4" value="4.4"/>
            <Entry name="Portara4.4" value="4.4"/>
        </FixVersion>

        @INCLUDE ./xml/model.fix.models.xml FIX_MODELS

        @INCLUDE ./xml/model.fix.models.dropcopy.xml FIX_DROP_COPY_MODELS

    </FixModels>

    <BinaryModels version="1.0.0" dir="../Generated/model/binary/version" rootPackage="com.rr.model.generated">
        @INCLUDE ./xml/model.euronext.cash.utp.xml EURONEXT_CASH_UTP_MODEL

        @INCLUDE ./xml/model.lse.millenium.xml LSE_MILLENIUM_MODEL

        @INCLUDE ./xml/model.lse.itch.xml LSE_ITCH_MODEL

        @INCLUDE ./xml/model.eurex.eti.xml EUREX_ETI_MODEL

        @INCLUDE ./xml/model.cme.sbe.xml CME_MODEL

        @INCLUDE ./xml/model.cboe.eu.tcp.pitch.xml TCP_PITCH_MODEL

        @INCLUDE ./xml/model.cboe.eu.tcp.pitch.historic.xml TCP_HISTORIC_PITCH_MODEL

        @INCLUDE ./xml/model.soup.xml SOUP_MODEL

    </BinaryModels>


    <!--

            MessageMapping: [FixMessageId] [EventId] { [handEncode] | [handDecode] } [Mapping]* ( [PostMapUserFunct] )
            Mapping: [TagId] [AttributeId] (MapInstruction) { [AttrUserFunct] | [ValueMap] }
            ValueMap : [FixValue][TypeEntryName]

            ORDER IS IMPORTANT, CODECS EXTENDING OTHER CODECS MUST APPEAR AFTER
    -->

    <Codecs version="1.0.0" dir="../Generated/model/codec-base/version" rootPackage="com.rr.model.generated.fix">
        @INCLUDE ./xml/model.fix.codecs.xml FIX_CODECS
        @INCLUDE ./xml/model.fix.codecs.dropcopy.xml FIX_DROP_COPY_CODECS
    </Codecs>

    <ExchangeCodecs version="1.0.0" dir="../Generated/model/codec-exchange/version" rootPackage="com.rr.model.generated.fix">
        <Codec id="CHIX" fix="4.2" type="Exchange" extends="Standard42"/>

        <Codec id="MDBSE" fix="MD5.0" extends="MD50" decodeInclude="BSEMDDecoder50.include" encodeInclude="BSEMDEncoder50.include"
               encodeBuilder="com.rr.core.codec.ReadableMDFastFixEncoder"
               decodeGenerator="com.rr.model.generator.customfix.BSEFixDecoderGenerator">
        </Codec>

        @INCLUDE ./xml/model.cme.fix.xml CME_EXCHANGE_CODEC

    </ExchangeCodecs>

    <ClientCodecs version="1.0.0" dir="../Generated/model/codec-client/version" rootPackage="com.rr.model.generated.fix">
        <Codec id="ClientX_44" fix="4.4" type="Client" extends="Standard44"/>
    </ClientCodecs>

    <BinaryCodecs version="1.0.0" dir="../Generated/model/codec-binary/version" rootPackage="com.rr.model.generated">
        @INCLUDE ./xml/model.euronext.cash.utp.xml EURONEXT_CASH_UTP_BINARY_CODEC

        @INCLUDE ./xml/model.lse.millenium.xml LSE_MILLENIUM_BINARY_CODEC

        @INCLUDE ./xml/model.lse.itch.xml LSE_ITCH_BINARY_CODEC

        @INCLUDE ./xml/model.eurex.eti.xml EUREX_ETI_BINARY_CODEC

        @INCLUDE ./xml/model.bse.eti.xml BSE_ETI_BINARY_CODEC

        @INCLUDE ./xml/model.cme.sbe.xml CME_SBE_CODEC

        @INCLUDE ./xml/model.cboe.eu.tcp.pitch.xml TCP_PITCH_BINARY_CODEC

        @INCLUDE ./xml/model.cboe.eu.tcp.pitch.historic.xml TCP_HISTORIC_PITCH_BINARY_CODEC

        @INCLUDE ./xml/model.soup.xml SOUP_CODEC

    </BinaryCodecs>

    <CodecFactories version="1.0.0" dir="../Generated/model/codec-factory/version" rootPackage="com.rr.model.generated.fix"/>

</Model>
